export const data = [
    {
        key: '1',
        year: '1991',
        Qty: 10,
        Description: 'New York No. 1 Lake Park',
        tags: ['nice', 'greate'],
      },
      {
        key: '2',
        year: '1992',
        Qty: 42,
        Description: 'London No. 1 Lake Park',
        tags: ['fire'],
      },
      {
        key: '3',
        year: '1993',
        Qty: 32,
        Description: 'Sydney No. 1 Lake Park',
        tags: ['cool', 'warm'],
      },
      {
        key: '4',
        year: '1994',
        Qty: 15,
        Description: 'Paris No. 1 Lake Park',
        tags: ['fun'],
      },
      {
        key: '5',
        year: '1995',
        Qty: 20,
        Description: 'Tokyo No. 1 Lake Park',
        tags: ['exciting', 'tourist'],
      },
      {
        key: '6',
        year: '1996',
        Qty: 28,
        Description: 'Berlin No. 1 Lake Park',
        tags: ['historical'],
      },
      {
        key: '7',
        year: '1997',
        Qty: 18,
        Description: 'Rome No. 1 Lake Park',
        tags: ['ancient'],
      },
      {
        key: '8',
        year: '1998',
        Qty: 36,
        Description: 'Moscow No. 1 Lake Park',
        tags: ['cold', 'vast'],
      },
      {
        key: '9',
        year: '1999',
        Qty: 25,
        Description: 'Madrid No. 1 Lake Park',
        tags: ['sunny', 'artistic'],
      },
      {
        key: '10',
        year: '2000',
        Qty: 50,
        Description: 'Beijing No. 1 Lake Park',
        tags: ['dynamic', 'cultural'],
      },
      // New items from key '11' to '20'
      {
        key: '11',
        year: '2001',
        Qty: 22,
        Description: 'Seoul No. 1 Lake Park',
        tags: ['modern', 'vibrant'],
      },
      {
        key: '12',
        year: '2002',
        Qty: 19,
        Description: 'Bangkok No. 1 Lake Park',
        tags: ['lively', 'exotic'],
      },
      {
        key: '13',
        year: '2003',
        Qty: 30,
        Description: 'Mexico City No. 1 Lake Park',
        tags: ['colorful', 'fiesta'],
      },
      {
        key: '14',
        year: '2004',
        Qty: 35,
        Description: 'Cairo No. 1 Lake Park',
        tags: ['historic', 'desert'],
      },
      {
        key: '15',
        year: '2005',
        Qty: 27,
        Description: 'Buenos Aires No. 1 Lake Park',
        tags: ['passionate', 'tango'],
      },
      {
        key: '16',
        year: '2006',
        Qty: 24,
        Description: 'Dubai No. 1 Lake Park',
        tags: ['luxurious', 'desert'],
      },
      {
        key: '17',
        year: '2007',
        Qty: 38,
        Description: 'Singapore No. 1 Lake Park',
        tags: ['modern', 'green'],
      },
      {
        key: '18',
        year: '2008',
        Qty: 31,
        Description: 'Istanbul No. 1 Lake Park',
        tags: ['historic', 'bridges'],
      },
      {
        key: '19',
        year: '2009',
        Qty: 29,
        Description: 'Hong Kong No. 1 Lake Park',
        tags: ['vibrant', 'metropolis'],
      },
      {
        key: '20',
        year: '2010',
        Qty: 45,
        Description: 'Mumbai No. 1 Lake Park',
        tags: ['bustling', 'coastal'],
      },
];
